version: '3.8'  # Secrets are only available since this version of Docker Compose
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: orthanc
      POSTGRES_USER: orthanc
      POSTGRES_PASSWORD: orthanc
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - orthanc-net

  orthanc:
    image: jodogne/orthanc-plugins
    ports:
      - 4242:4242
      - 8042:8042
    environment:
      # - ORTHANC_JSON_CONFIG=/etc/orthanc/orthanc.json
      - ORTHANC__DatabaseBackend=PostgreSQL
      - ORTHANC__PostgreSQL__EnableIndex=true
      - ORTHANC__PostgreSQL__Host=postgres
      - ORTHANC__PostgreSQL__Port=5432
      - ORTHANC__PostgreSQL__Database=orthanc
      - ORTHANC__PostgreSQL__Username=orthanc_adm
      - ORTHANC__PostgreSQL__Password=orthanc
    volumes:
      # - ./orthanc.json:/etc/orthanc/orthanc.json
      - orthanc_data:/var/lib/orthanc
    networks:
      - orthanc-net
    depends_on:
      - postgres
      

networks:
  orthanc-net:

volumes:
  postgres_data:
  orthanc_config:
  orthanc_data:
