version: "3.8"
services:
  orthanc-file-in-env-var:
    image: orthancteam/orthanc
    depends_on:
      - postgres  # Ensure this matches the service name defined below
    ports: ["8200:8042"]
    environment:
      VERBOSE_STARTUP: "true"
      VERBOSE_ENABLED: "true" 
      POSTGRESQL_PLUGIN_ENABLED: "true"
      VOLVIEW_PLUGIN_ENABLED: "true"
      OHIF_PLUGIN_ENABLED: "true"
      ORTHANC_WEB_VIEWER_PLUGIN_ENABLED: "true"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      TRANSFERS_PLUGIN_ENABLED: "true"
      PYTHON_PLUGIN_ENABLED: "true"
      # OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
    volumes:
      - ./script/hello.py:/etc/orthanc/hello.py:ro
      - ./ai_trigger.lua:/etc/orthanc/ai_trigger.lua:ro
    secrets:
      - orthanc.secret.json
    networks:
      - orthanc-net

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: orthanc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_pw
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - orthanc-net

secrets:
    orthanc.secret.json:
      file: orthanc.secret.json

volumes:
  postgres_data:

networks:
  orthanc-net: